//	============================================================================
//
//  .,-:::::   :::.    :::::::..   :::::::.      ...   :::.    :::.
//	,;;;'````'   ;;`;;   ;;;;``;;;;   ;;;'';;'  .;;;;;;;.`;;;;,  `;;;
//	[[[         ,[[ '[[,  [[[,/[[['   [[[__[[\.,[[     \[[,[[[[[. '[[
//	$$$        c$$$cc$$$c $$$$$$c     $$""""Y$$$$$,     $$$$$$ "Y$c$$
//	`88bo,__,o, 888   888,888b "88bo,_88o,,od8P"888,_ _,88P888    Y88
//	"YUMMMMMP"YMM   ""` MMMM   "W" ""YUMMMP"   "YMMMMMP" MMM     YM
//
//	============================================================================
//
//	This file is a part of the Carbon Framework.
//
//	Copyright (C) 2005 Mark (Code6) Belles 
//
//	This library is free software; you can redistribute it and/or
//	modify it under the terms of the GNU Lesser General Public
//	License as published by the Free Software Foundation; either
//	version 2.1 of the License, or (at your option) any later version.
//
//	This library is distributed in the hope that it will be useful,
//	but WITHOUT ANY WARRANTY; without even the implied warranty of
//	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
//	Lesser General Public License for more details.
//
//	You should have received a copy of the GNU Lesser General Public
//	License along with this library; if not, write to the Free Software
//	Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
//
//	============================================================================

using System;

namespace Carbon.Networking.Http
{
	/// <summary>
	/// [RFC2045,RFC2046] specifies that Content Types, Content Subtypes, Character Sets, Access Types, and conversion values for MIME mail will be assigned and listed by the IANA.
	///	The following is the list of Directories of Content Types and Subtypes.
	/// </summary>
	public static class MIME
	{
//		public class application
//		{
//			public readonly static string X = @"activemessage"     ; // [Shapiro]
//			public readonly static string X = @"andrew-inset"   ; // [Borenstein]
//			public readonly static string X = @"applefile"   ; // [Faltstrom]
//			public readonly static string X = @"atomicmail"  ; // [Borenstein]
//			public readonly static string X = @"batch-SMTP"  ; // [RFC2442]
//			public readonly static string X = @"beep+xml"    ; // [RFC3080]
//			public readonly static string X = @"cals-1840"   ; // [RFC1895]
//			public readonly static string X = @"cnrp+xml"    ; // [RFCCNRP]
//			public readonly static string X = @"commonground"   ; // [Glazer]
//			public readonly static string X = @"cpl+xml"  ; // [RFC-ietf-iptel-cpl-09.txt]
//			public readonly static string X = @"cybercash"   ; // [Eastlake]
//			public readonly static string X = @"dca-rft"  ; // [Campbell]
//			public readonly static string X = @"dec-dx"   ; // [Campbell]
//			public readonly static string X = @"dicom"    ; // [RFC3240]
//			public readonly static string X = @"dns"   ; // [RFC-josefsson-mime-dns-02.txt]
//			public readonly static string X = @"dvcs" ; // [RFC3029]
//			public readonly static string X = @"EDI-Consent"    ; // [RFC1767]
//			public readonly static string X = @"EDIFACT"  ; // [RFC1767]
//			public readonly static string X = @"EDI-X12"  ; // [RFC1767]
//			public readonly static string X = @"epp+xml"  ; // [RFC3730]
//			public readonly static string X = @"eshop"    ; // [Katz]
//			public readonly static string X = @"fits"  ; // [RFC-allen-fitsmime-00.txt]
//			public readonly static string X = @"font-tdpfr"  ; // [RFC3073]
//			public readonly static string X = @"http"  ; // [RFC2616]
//			public readonly static string X = @"hyperstudio"    ; // [Domino]
//			public readonly static string X = @"iges"  ; // [Parks]
//			public readonly static string X = @"im-iscomposing+xml"   ; // [RFC-ietf-simple-iscomposing-03.txt]
//			public readonly static string X = @"index"    ; // [RFC2652]
//			public readonly static string X = @"index.cmd"   ; // [RFC2652]
//			public readonly static string X = @"index.obj"   ; // [RFC2652]
//			public readonly static string X = @"index.response"    ; // [RFC2652]
//			public readonly static string X = @"index.vnd"   ; // [RFC2652]
//			public readonly static string X = @"iotp"  ; // [RFC2935]
//			public readonly static string X = @"ipp"   ; // [RFC2910]
//			public readonly static string X = @"isup"  ; // [RFC3204]
//			public readonly static string X = @"mac-binhex40"   ; // [Faltstrom]
//			public readonly static string X = @"macwriteii"  ; // [Lindner]
//			public readonly static string X = @"marc"  ; // [RFC2220]
//			public readonly static string X = @"mathematica"    ; // [Van Nostern]
//			public readonly static string X = @"mikey"    ; // [RFC3830]
//			public readonly static string X = @"mpeg4-generic"  ; // [RFC3640]
//			public readonly static string X = @"msword"   ; // [Lindner]
//			public readonly static string X = @"news-message-id"   ; // [RFC1036,Spencer]
//			news-transmission    ; // [RFC1036, Spencer]
//			ocsp-request   ; // [RFC2560]
//			ocsp-response  ; // [RFC2560]
//			octet-stream   ; // [RFC2045,RFC2046]
//			oda   ; // [RFC2045,RFC2046]
//			ogg   ; // [RFC3534]
//			parityfec   ; // [RFC3009]
//			pdf   ; // [RFC3778]
//			pgp-encrypted  ; // [RFC3156]
//			pgp-keys    ; // [RFC3156]
//			pgp-signature  ; // [RFC3156]
//			pidf+xml    ; // [RFC3863]
//			pkcs10   ; // [RFC2311]
//			pkcs7-mime  ; // [RFC2311]
//			pkcs7-signature   ; // [RFC2311]
//			pkix-cert   ; // [RFC2585]
//			pkixcmp  ; // [RFC2510]
//			pkix-crl    ; // [RFC2585]
//			pkix-pkipath   ; // [RFC3546]
//			postscript  ; // [RFC2045,RFC2046]
//			prs.alvestrand.titrax-sheet   ; // [Alvestrand]
//			prs.cww  ; // [Rungchavalnont]
//			prs.nprend  ; // [Doggett]
//			prs.plucker    ; // [Janssen]
//			rdf+xml  ; // [RFC3870]
//			qsig  ; // [RFC3204]
//			reginfo+xml    ; // [RFC3680]
//			remote-printing   ; // [RFC1486,Rose]
//			riscos   ; // [Smith]
//			rtf   ; // [Lindner]
//			samlassertion+xml    ; // [OASIS Security Services Technical Committee (SSTC)]
//			samlmetadata+xml  ; // [OASIS Security Services Technical Committee (SSTC)]
//			sbml+xml    ; // [RFC3823]
//			sdp   ; // [RFC2327]
//			set-payment    ; // [Korver]
//			set-payment-initiation  ; // [Korver]
//			set-registration  ; // [Korver]
//			set-registration-initiation   ; // [Korver]
//			sgml  ; // [RFC1874]
//			sgml-open-catalog    ; // [Grosso]
//			sieve    ; // [RFC3028]
//			simple-message-summary  ; // [RFC3842]
//			slate    ; // [Crowley]
//			soap+xml    ; // [RFC3902]
//			spirits-event+xml    ; // [RFC3910]
//			timestamp-query   ; // [RFC3161]
//			timestamp-reply   ; // [RFC3161]
//			tve-trigger    ; // [Welsh]
//			vemmi    ; // [RFC2122]
//			vnd.3gpp.pic-bw-large   ; // [Meredith]
//			vnd.3gpp.pic-bw-small   ; // [Meredith]
//			vnd.3gpp.pic-bw-var  ; // [Meredith]
//			vnd.3gpp.sms   ; // [Meredith]
//			vnd.3M.Post-it-Notes    ; // [O'Brien]
//			vnd.accpac.simply.aso   ; // [Leow]
//			vnd.accpac.simply.imp   ; // [Leow]
//			vnd.acucobol   ; // [Lubin]
//			vnd.acucorp    ; // [Lubin]
//			vnd.adobe.xfdf    ; // [Perelman]
//			vnd.aether.imp    ; // [Moskowitz]
//			vnd.amiga.ami  ; // [Blumberg]
//			vnd.anser-web-certificate-issue-initiation   ; // [Mori]
//			vnd.anser-web-funds-transfer-initiation   ; // [Mori]
//			vnd.audiograph    ; // [Slusanschi]
//			vnd.blueice.multipass   ; // [Holmstrom]
//			vnd.bmi  ; // [Gotoh]
//			vnd.businessobjects  ; // [Imoucha]
//			vnd.canon-cpdl    ; // [Muto]
//			vnd.canon-lips    ; // [Muto]
//			vnd.cinderella    ; // [Kortenkamp]
//			vnd.claymore   ; // [Simpson]
//			vnd.commerce-battelle   ; // [Applebaum]
//			vnd.commonspace   ; // [Chandhok]
//			vnd.cosmocaller   ; // [Dellutri]
//			vnd.contact.cmsg  ; // [Patz]
//			vnd.criticaltools.wbs+xml  ; // [Spiller]
//			vnd.ctc-posml  ; // [Kohlhepp]
//			vnd.cups-postscript  ; // [Sweet]
//			vnd.cups-raster   ; // [Sweet]
//			vnd.cups-raw   ; // [Sweet]
//			vnd.curl    ; // [Byrnes]
//			vnd.cybank  ; // [Helmee]
//			vnd.data-vision.rdz  ; // [Fields]
//			vnd.dna  ; // [Searcy]
//			vnd.dpgraph    ; // [Parker]
//			vnd.dreamfactory  ; // [Appleton]
//			vnd.dxr  ; // [Duffy]
//			vnd.ecdis-update  ; // [Buettgenbach]
//			vnd.ecowin.chart  ; // [Olsson]
//			vnd.ecowin.filerequest  ; // [Olsson]
//			vnd.ecowin.fileupdate   ; // [Olsson]
//			vnd.ecowin.series    ; // [Olsson]
//			vnd.ecowin.seriesrequest   ; // [Olsson]
//			vnd.ecowin.seriesupdate    ; // [Olsson]
//			vnd.enliven    ; // [Santinelli]
//			vnd.epson.esf  ; // [Hoshina]
//			vnd.epson.msf  ; // [Hoshina]
//			vnd.epson.quickanime    ; // [Gu]
//			vnd.epson.salt    ; // [Nagatomo]
//			vnd.epson.ssf  ; // [Hoshina]
//			vnd.ericsson.quickcall  ; // [Tidwell]
//			vnd.eudora.data   ; // [Resnick]
//			vnd.fdf  ; // [Zilles]
//			vnd.ffsns   ; // [Holstage]
//			vnd.fints   ; // [Hammann]
//			vnd.FloGraphIt    ; // [Floersch]
//			vnd.framemaker    ; // [Wexler]
//			vnd.fsc.weblaunch    ; // [D.Smith]
//			vnd.fujitsu.oasys    ; // [Togashi]
//			vnd.fujitsu.oasys2   ; // [Togashi]
//			vnd.fujitsu.oasys3   ; // [Okudaira]
//			vnd.fujitsu.oasysgp  ; // [Sugimoto]
//			vnd.fujitsu.oasysprs    ; // [Ogita]
//			vnd.fujixerox.ddd    ; // [Onda]
//			vnd.fujixerox.docuworks    ; // [Taguchi]
//			vnd.fujixerox.docuworks.binder   ; // [Matsumoto]
//			vnd.fut-misnet    ; // [Pruulmann]
//			vnd.genomatix.tuxedo    ; // [Frey]
//			vnd.grafeq  ; // [Tupper]
//			vnd.groove-account   ; // [Joseph]
//			vnd.groove-help   ; // [Joseph]
//			vnd.groove-identity-message   ; // [Joseph]
//			vnd.groove-injector  ; // [Joseph]
//			vnd.groove-tool-message    ; // [Joseph]
//			vnd.groove-tool-template   ; // [Joseph]
//			vnd.groove-vcard  ; // [Joseph]
//			vnd.hbci    ; // [Hammann]
//			vnd.hcl-bireports    ; // [Serres]
//			vnd.hhe.lesson-player   ; // [Jones]
//			vnd.hp-HPGL    ; // [Pentecost]
//			vnd.hp-hpid    ; // [Gupta]
//			vnd.hp-hps  ; // [Aubrey]
//			vnd.hp-PCL  ; // [Pentecost]
//			vnd.hp-PCLXL   ; // [Pentecost]
//			vnd.httphone   ; // [Lefevre]
//			vnd.hzn-3d-crossword    ; // [Minnis]
//			vnd.ibm.afplinedata  ; // [Buis]
//			vnd.ibm.electronic-media   ; // [Tantlinger]
//			vnd.ibm.MiniPay   ; // [Herzberg]
//			vnd.ibm.modcap    ; // [Hohensee]
//			vnd.ibm.rights-management  ; // [Tantlinger]
//			vnd.ibm.secure-container   ; // [Tantlinger]
//			vnd.informix-visionary  ; // [Gales]
//			vnd.intercon.formnet    ; // [Gurak]
//			vnd.intertrust.digibox  ; // [Tomasello]
//			vnd.intertrust.nncp  ; // [Tomasello]
//			vnd.intu.qbo   ; // [Scratchley]
//			vnd.intu.qfx   ; // [Scratchley]
//			vnd.ipunplugged.rcprofile  ; // [Ersson]
//			vnd.irepository.package+xml   ; // [Knowles]
//			vnd.is-xpr  ; // [Natarajan]
//			vnd.japannet-directory-service   ; // [Fujii]
//			vnd.japannet-jpnstore-wakeup  ; // [Yoshitake]
//			vnd.japannet-payment-wakeup   ; // [Fujii]
//			vnd.japannet-registration  ; // [Yoshitake]
//			vnd.japannet-registration-wakeup    ; // [Fujii]
//			vnd.japannet-setstore-wakeup  ; // [Yoshitake]
//			vnd.japannet-verification  ; // [Yoshitake]
//			vnd.japannet-verification-wakeup    ; // [Fujii]
//			vnd.jisp    ; // [Deckers]
//			vnd.kde.karbon    ; // [Faure]
//			vnd.kde.kchart    ; // [Faure]
//			vnd.kde.kformula  ; // [Faure]
//			vnd.kde.kivio  ; // [Faure]
//			vnd.kde.kontour   ; // [Faure]
//			vnd.kde.kpresenter   ; // [Faure]
//			vnd.kde.kspread   ; // [Faure]
//			vnd.kde.kword  ; // [Faure]
//			vnd.kenameaapp    ; // [DiGiorgio-Haag]
//			vnd.kidspiration  ; // [Bennett]
//			vnd.Kinar   ; // [Thakkar]
//			vnd.koan    ; // [Cole]
//			vnd.liberty-request+xml    ; // [McDowell]
//			vnd.llamagraphics.life-balance.desktop    ; // [White]
//			vnd.llamagraphics.life-balance.exchange+xml  ; // [White]
//			vnd.lotus-1-2-3   ; // [Wattenberger]
//			vnd.lotus-approach   ; // [Wattenberger]
//			vnd.lotus-freelance  ; // [Wattenberger]
//			vnd.lotus-notes   ; // [Laramie]
//			vnd.lotus-organizer  ; // [Wattenberger]
//			vnd.lotus-screencam  ; // [Wattenberger]
//			vnd.lotus-wordpro    ; // [Wattenberger]
//			vnd.mcd  ; // [Gotoh]
//			vnd.mediastation.cdkey  ; // [Flurry]
//			vnd.meridian-slingshot  ; // [Wedel]
//			vnd.mfmp    ; // [Ikeda]
//			vnd.micrografx.flo   ; // [Prevo]
//			vnd.micrografx.igx   ; // [Prevo]
//			vnd.mif  ; // [Wexler]
//			vnd.minisoft-hp3000-save   ; // [Bartram]
//			vnd.mitsubishi.misty-guard.trustweb    ; // [Tanaka]
//			vnd.Mobius.DAF    ; // [Kabayama]
//			vnd.Mobius.DIS    ; // [Kabayama]
//			vnd.Mobius.MBK    ; // [Devasia]
//			vnd.Mobius.MQY    ; // [Devasia]
//			vnd.Mobius.MSL    ; // [Kabayama]
//			vnd.Mobius.PLC    ; // [Kabayama]
//			vnd.Mobius.TXF    ; // [Kabayama]
//			vnd.mophun.application  ; // [Wennerstrom]
//			vnd.mophun.certificate  ; // [Wennerstrom]
//			vnd.motorola.flexsuite  ; // [Patton]
//			vnd.motorola.flexsuite.adsi   ; // [Patton]
//			vnd.motorola.flexsuite.fis    ; // [Patton]
//			vnd.motorola.flexsuite.gotap  ; // [Patton]
//			vnd.motorola.flexsuite.kmr    ; // [Patton]
//			vnd.motorola.flexsuite.ttc    ; // [Patton]
//			vnd.motorola.flexsuite.wem    ; // [Patton]
//			vnd.mozilla.xul+xml  ; // [McDaniel]
//			vnd.ms-artgalry   ; // [Slawson]
//			vnd.ms-asf  ; // [Fleischman]
//			vnd.mseq    ; // [Le Bodic]
//			vnd.ms-excel   ; // [Gill]
//			vnd.msign   ; // [Borcherding]
//			vnd.ms-lrm  ; // [Ledoux]
//			vnd.ms-powerpoint    ; // [Gill]
//			vnd.ms-project    ; // [Gill]
//			vnd.ms-tnef    ; // [Gill]
//			vnd.ms-works   ; // [Gill]
//			vnd.ms-wpl  ; // [Plastina]
//			vnd.musician   ; // [Adams]
//			vnd.music-niff    ; // [Butler]
//			vnd.nervana    ; // [Judkins]
//			vnd.netfpx  ; // [Mutz]
//			vnd.noblenet-directory  ; // [Solomon]
//			vnd.noblenet-sealer  ; // [Solomon]
//			vnd.noblenet-web  ; // [Solomon]
//			vnd.nokia.landmark+xml  ; // [Nokia]
//			vnd.nokia.landmark+wbxml   ; // [Nokia]
//			vnd.nokia.landmarkcollection+xml    ; // [Nokia]
//			vnd.nokia.radio-preset  ; // [Nokia]
//			vnd.nokia.radio-presets    ; // [Nokia]
//			vnd.novadigm.EDM  ; // [Swenson]
//			vnd.novadigm.EDX  ; // [Swenson]
//			vnd.novadigm.EXT  ; // [Swenson]
//			vnd.obn  ; // [Hessling]
//			vnd.omads-email+xml  ; // [OMA Data Synchronization Working Group]
//			vnd.omads-file+xml   ; // [OMA Data Synchronization Working Group]
//			vnd.omads-folder+xml    ; // [OMA Data Synchronization Working Group]
//			vnd.osa.netdeploy    ; // [Klos]
//			vnd.palm    ; // [Peacock]
//			vnd.paos.xml   ; // [Kemp]
//			vnd.pg.format  ; // [Gandert]
//			vnd.picsel  ; // [Naccarato]
//			vnd.pg.osasli  ; // [Gandert]
//			vnd.powerbuilder6    ; // [Guy]
//			vnd.powerbuilder6-s  ; // [Guy]
//			vnd.powerbuilder7    ; // [Shilts]
//			vnd.powerbuilder75   ; // [Shilts]
//			vnd.powerbuilder75-s    ; // [Shilts]
//			vnd.powerbuilder7-s  ; // [Shilts]
//			vnd.previewsystems.box  ; // [Smolgovsky]
//			vnd.publishare-delta-tree  ; // [Ben-Kiki]
//			vnd.pvi.ptid1  ; // [Lamb]
//			vnd.pwg-multiplexed  ; // [RFC3391]
//			vnd.pwg-xhtml-print+xml    ; // [Wright]
//			vnd.Quark.QuarkXPress   ; // [Scheidler]
//			vnd.rapid   ; // [Szekely]
//			vnd.RenLearn.rlprint    ; // [Wick]
//			vnd.s3sms   ; // [Tarkkala]
//			vnd.sealed.doc    ; // [Petersen]
//			vnd.sealed.eml    ; // [Petersen]
//			vnd.sealed.mht    ; // [Petersen]
//			vnd.sealed.net    ; // [Lambert]
//			vnd.sealed.ppt    ; // [Petersen]
//			vnd.sealed.xls    ; // [Petersen]
//			vnd.sealedmedia.softseal.html    ; // [Petersen]
//			vnd.sealedmedia.softseal.pdf  ; // [Petersen]
//			vnd.seemail    ; // [Webb]
//			vnd.shana.informed.formdata   ; // [Selzler]
//			vnd.shana.informed.formtemplate  ; // [Selzler]
//			vnd.shana.informed.interchange   ; // [Selzler]
//			vnd.shana.informed.package    ; // [Selzler]
//			vnd.smaf    ; // [Takahashi]
//			vnd.sss-cod    ; // [Dani]
//			vnd.sss-dtf    ; // [Bruno]
//			vnd.sss-ntf    ; // [Bruno]
//			vnd.street-stream    ; // [Levitt]
//			vnd.sus-calendar  ; // [Niedfeldt]
//			vnd.svd  ; // [Becker]
//			vnd.swiftview-ics    ; // [Widener]
//			vnd.syncml.ds.notification    ; // [OMA Data Synchronization Working Group]
//			vnd.syncml.+xml   ; // [OMA Data Synchronization Working Group]
//			vnd.triscape.mxs  ; // [Simonoff]
//			vnd.trueapp    ; // [Hepler]
//			vnd.truedoc    ; // [Chase]
//			vnd.ufdl    ; // [Manning]
//			vnd.uiq.theme  ; // [Ocock]
//			vnd.uplanet.alert    ; // [Martin]
//			vnd.uplanet.alert-wbxml    ; // [Martin]
//			vnd.uplanet.bearer-choice  ; // [Martin]
//			vnd.uplanet.bearer-choice-wbxml  ; // [Martin]
//			vnd.uplanet.cacheop  ; // [Martin]
//			vnd.uplanet.cacheop-wbxml  ; // [Martin]
//			vnd.uplanet.channel  ; // [Martin]
//			vnd.uplanet.channel-wbxml  ; // [Martin]
//			vnd.uplanet.list  ; // [Martin]
//			vnd.uplanet.listcmd  ; // [Martin]
//			vnd.uplanet.listcmd-wbxml  ; // [Martin]
//			vnd.uplanet.list-wbxml  ; // [Martin]
//			vnd.uplanet.signal   ; // [Martin]
//			vnd.vcx  ; // [T.Sugimoto]
//			vnd.vectorworks   ; // [Pharr]
//			vnd.vidsoft.vidconference  ; // [Hess]
//			vnd.visio   ; // [Sandal]
//			vnd.visionary  ; // [Aravindakumar]
//			vnd.vividence.scriptfile   ; // [Risher]
//			vnd.vsf  ; // [Rowe]
//			vnd.wap.sic    ; // [WAP-Forum]
//			vnd.wap.slc    ; // [WAP-Forum]
//			vnd.wap.wbxml  ; // [Stark]
//			vnd.wap.wmlc   ; // [Stark]
//			vnd.wap.wmlscriptc   ; // [Stark]
//			vnd.webturbo   ; // [Rehem]
//			vnd.wordperfect   ; // [Scarborough]
//			vnd.wqd  ; // [Bostrom]
//			vnd.wrq-hp3000-labelled    ; // [Bartram]
//			vnd.wt.stf  ; // [Wohler]
//			vnd.wv.csp+xml    ; // [Ingimundarson]
//			vnd.wv.csp+wbxml  ; // [Salmi]
//			vnd.wv.ssp+xml    ; // [Ingimundarson]
//			vnd.xara    ; // [Matthewman]
//			vnd.xfdl    ; // [Manning]
//			vnd.yamaha.hv-dic    ; // [Yamamoto]
//			vnd.yamaha.hv-script    ; // [Yamamoto]
//			vnd.yamaha.hv-voice  ; // [Yamamoto]
//			vnd.yamaha.smaf-audio   ; // [Shinoda]
//			vnd.yamaha.smaf-phrase  ; // [Shinoda]
//			vnd.yellowriver-custom-menu   ; // [Yellow]
//			watcherinfo+xml   ; // [RFC3858]
//			whoispp-query  ; // [RFC2957]
//			whoispp-response  ; // [RFC2958]
//			wita  ; // [Campbell]
//			wordperfect5.1    ; // [Lindner]
//			x400-bp  ; // [RFC1494]
//			xhtml+xml   ; // [RFC3236]
//			xml   ; // [RFC3023]
//			xml-dtd  ; // [RFC3023]
//			xml-external-parsed-entity    ; // [RFC3023]
//			xmpp+xml    ; // [RFC3923]
//			xop+xml  ; // [Nottingham]
//			zip   ; // [Lindner]
//		}

//		public class audio
//		{
//			public readonly static string X = @"32kadpcm  	; // [RFC2421,RFC2422]
//			public readonly static string X = @"3gpp 	; // [RFC3839]
//			public readonly static string X = @"AMR 	; // [RFC3267]
//			public readonly static string X = @"AMR-WB 	; // [RFC3267]
//			public readonly static string X = @"basic 	; // [RFC2045,RFC2046]
//			public readonly static string X = @"clearmode 	; // [RFC-draft-ietf-avt-rtp-clearmode-05.txt]
//			public readonly static string X = @"CN 	; // [RFC3389]
//			public readonly static string X = @"DAT12 	; // [RFC3190]
//			public readonly static string X = @"dsr-es201108 	; // [RFC3557]
//			public readonly static string X = @"dsr-es202050 	; // [RFC-ietf-avt-rtp-dsr-codecs-03.txt]
//			public readonly static string X = @"dsr-es202211 	; // [RFC-ietf-avt-rtp-dsr-codecs-03.txt]
//			public readonly static string X = @"dsr-es202212 	; // [RFC-ietf-avt-rtp-dsr-codecs-03.txt]
//			public readonly static string X = @"DVI4 	; // [RFC3555]
//			public readonly static string X = @"EVRC 	; // [RFC3558]
//			public readonly static string X = @"EVRC0 	; // [RFC3558]
//			public readonly static string X = @"EVRC-QCP 	; // [RFC3625]
//			public readonly static string X = @"G722 	; // [RFC3555]
//			public readonly static string X = @"G.722.1 	; // [RFC3047]
//			public readonly static string X = @"G723 	; // [RFC3555]
//			public readonly static string X = @"G726-16 	; // [RFC3555]
//			public readonly static string X = @"G726-24 	; // [RFC3555]
//			public readonly static string X = @"G726-32 	; // [RFC3555]
//			public readonly static string X = @"G726-40 	; // [RFC3555]
//			public readonly static string X = @"G728 	; // [RFC3555]
//			public readonly static string X = @"G729 	; // [RFC3555]
//			public readonly static string X = @"G729D 	; // [RFC3555]
//			public readonly static string X = @"G729E 	; // [RFC3555]
//			public readonly static string X = @"GSM 	; // [RFC3555]
//			public readonly static string X = @"GSM-EFR 	; // [RFC3555]
//			public readonly static string X = @"iLBC 	; // [RFC-ietf-avt-rtp-ilbc-05.txt]
//			public readonly static string X = @"L8 	; // [RFC3555]
//			public readonly static string X = @"L16 	; // [RFC3555]
//			public readonly static string X = @"L20 	; // [RFC3190]
//			public readonly static string X = @"L24 	; // [RFC3190]
//			public readonly static string X = @"LPC 	; // [RFC3555]
//			public readonly static string X = @"MPA 	; // [RFC3555]
//			public readonly static string X = @"MP4A-LATM 	; // [RFC3016]
//			public readonly static string X = @"mpa-robust 	; // [RFC3119]
//			public readonly static string X = @"mpeg 	; // [RFC3003]
//			public readonly static string X = @"mpeg4-generic 	; // [RFC3640]
//			public readonly static string X = @"parityfec 	; // [RFC3009]
//			public readonly static string X = @"PCMA 	; // [RFC3555]
//			public readonly static string X = @"PCMU 	; // [RFC3555]
//			public readonly static string X = @"prs.sid 	; // [Walleij]
//			public readonly static string X = @"QCELP 	; // [RFC3555]; // [RFC3625]
//			public readonly static string X = @"RED 	; // [RFC3555]
//			public readonly static string X = @"SMV 	; // [RFC3558]
//			public readonly static string X = @"SMV0 	; // [RFC3558]
//			public readonly static string X = @"SMV-QCP 	; // [RFC3625]
//			public readonly static string X = @"telephone-event 	; // [RFC2833]
//			public readonly static string X = @"tone 	; // [RFC2833]
//			public readonly static string X = @"VDVI 	; // [RFC3555]
//			public readonly static string X = @"vnd.3gpp.iufp 	; // [Belling]
//			public readonly static string X = @"vnd.audiokoz 	; // [DeBarros]
//			public readonly static string X = @"vnd.cisco.nse 	; // [Kumar]
//			public readonly static string X = @"vnd.cns.anp1 	; // [McLaughlin]
//			public readonly static string X = @"vnd.cns.inf1 	; // [McLaughlin]
//			public readonly static string X = @"vnd.digital-winds 	; // [Strazds]
//			public readonly static string X = @"vnd.everad.plj 	; // [Cicelsky]
//			public readonly static string X = @"vnd.lucent.voice 	; // [Vaudreuil]
//			public readonly static string X = @"vnd.nokia.mobile-xmf 	; // [Nokia Corporation]
//			public readonly static string X = @"vnd.nortel.vbk 	; // [Parsons]
//			public readonly static string X = @"vnd.nuera.ecelp4800 	; // [Fox]
//			public readonly static string X = @"vnd.nuera.ecelp7470 	; // [Fox]
//			public readonly static string X = @"vnd.nuera.ecelp9600 	; // [Fox]
//			public readonly static string X = @"vnd.octel.sbc 	; // [Vaudreuil]
//			public readonly static string X = @"vnd.qcelp - DEPRECATED - Please use audio/qcelp 	; // [RFC3625]
//			public readonly static string X = @"vnd.rhetorex.32kadpcm 	; // [Vaudreuil]
//			public readonly static string X = @"vnd.sealedmedia.softseal.mpeg 	; // [Petersen]
//			public readonly static string X = @"vnd.vmx.cvsd 	; // [Vaudreuil]
//		}

        /// <summary>
        /// Defines the known MIME types for images.
        /// </summary>
		public static class Image
		{
			public readonly static string Cgm										= @"image/cgm"; // [Francis]
			public readonly static string Fits									= @"image/fits"     ; // [RFC-allen-fitsmime-00.txt]
			public readonly static string G3fax									= @"image/g3fax"      ; // [RFC1494]
			public readonly static string Gif										= @"image/gif"       ; // [RFC2045,RFC2046]
			public readonly static string Ief										= @"image/ief"      ; // [RFC1314]
			public readonly static string Jp2										= @"image/jp2"       ; // [RFC3745]
			public readonly static string Jpeg									= @"image/jpeg"           ; // [RFC2045,RFC2046]
			public readonly static string Jpm										= @"image/jpm"       ; // [RFC3745]
			public readonly static string Jpx										= @"image/jpx"       ; // [RFC3745]
			public readonly static string Naplps									= @"image/naplps"       ; // [Ferber]
			public readonly static string Png										= @"image/png"       ; // [Randers-Pehrson]
			public readonly static string Prs_btif								= @"image/prs.btif"      ; // [Simon]
			public readonly static string Prs_pti									= @"image/prs.pti"     ; // [Laun]
			public readonly static string T38										= @"image/t38"       ; // [RFC3362]
			public readonly static string Tiff									= @"image/tiff"     ; // [RFC3302]
			public readonly static string Tiff_fx									= @"image/tiff-fx"  ; // [RFC-draft-ietf-fax-tiff-fx-reg-v2-01.txt]
			public readonly static string Vnd_cns_inf2							= @"image/vnd.cns.inf2"       ; // [McLaughlin]
			public readonly static string Vnd_djvu								= @"image/vnd.djvu"      ; // [Bottou]
			public readonly static string Vnd_dwg									= @"image/vnd.dwg"     ; // [Moline]
			public readonly static string Vnd_dxf									= @"image/vnd.dxf"     ; // [Moline]
			public readonly static string Vnd_fastbidsheet						= @"image/vnd.fastbidsheet"     ; // [Becker]
			public readonly static string Vnd_fpx									= @"image/vnd.fpx"     ; // [Spencer]
			public readonly static string Vnd_fst									= @"image/vnd.fst"     ; // [Fuldseth]
			public readonly static string Vnd_fujixerox_edmics_mmr				= @"image/vnd.fujixerox.edmics-mmr"       ; // [Onda]
			public readonly static string Vnd_fujixerox_edmics_rlc				= @"image/vnd.fujixerox.edmics-rlc"       ; // [Onda]
			public readonly static string Vnd_globalgraphics_pgb					= @"image/vnd.globalgraphics.pgb"     ; // [Bailey]
			public readonly static string Vnd_microsoft_icon						= @"image/vnd.microsoft.icon"       ; // [Butcher]
			public readonly static string Vnd_mix									= @"image/vnd.mix"     ; // [Reddy]
			public readonly static string Vnd_ms_modi								= @"image/vnd.ms-modi"      ; // [Vaughan]
			public readonly static string Vnd_net_fpx								= @"image/vnd.net-fpx"      ; // [Spencer]
			public readonly static string Vnd_sealed_png							= @"image/vnd.sealed.png"      ; // [Petersen]
			public readonly static string Vnd_sealedmedia_softseal_gif			= @"image/vnd.sealedmedia.softseal.gif"     ; // [Petersen]
			public readonly static string Vnd_sealedmedia_softseal_jpg			= @"image/vnd.sealedmedia.softseal.jpg"     ; // [Petersen]
			public readonly static string Vnd_svf									= @"image/vnd.svf"     ; // [Moline]
			public readonly static string Vnd_wap_wbmp							= @"image/vnd.wap.wbmp"       ; // [Stark]
			public readonly static string Vnd_xiff								= @"image/vnd.xiff"      ; // [S.Martin]
		}

//		public class Message
//		{
//			public readonly static string cpim									= @"message/CPIM"     ; // [RFC3862]
//			public readonly static string delivery_status							= @"message/delivery-status"    ; // [RFC1894]
//			public readonly static string disposition_notification				= @"message/disposition-notification"    ; // [RFC2298]
//			public readonly static string external_body							= @"message/external-body"  ; // [RFC2045,RFC2046]
//			public readonly static string http									= @"message/http"  ; // [RFC2616]
//			public readonly static string news									= @"message/news"  ; // [RFC 1036, H.Spencer]
//			public readonly static string partial									= @"message/partial"  ; // [RFC2045,RFC2046]
//			public readonly static string rfc822									= @"message/rfc822"    ; // [RFC2045,RFC2046]
//			public readonly static string s_http									= @"message/s-http"    ; // [RFC2660]
//			public readonly static string sip										= @"message/sip"    ; // [RFC3261]
//			public readonly static string sipfrag									= @"message/sipfrag"  ; // [RFC3420]
//			public readonly static string tracking_status							= @"message/tracking-status"    ; // [RFC3886]
//		}

//		public class Model
//		{
//			public readonly static string iges									= @"model/iges"     ; // [Parks]
//			public readonly static string mesh									= @"model/mesh"  ; // [RFC2077]
//			public readonly static string Vnd_dwf									= @"model/vnd.dwf"  ; // [Pratt]
//			public readonly static string Vnd_flatland_3dml						= @"model/vnd.flatland.3dml"   ; // [Powers]
//			public readonly static string Vnd_gdl									= @"model/vnd.gdl"  ; // [Babits]
//			public readonly static string Vnd_gs_gdl								= @"model/vnd.gs-gdl"  ; // [Babits]
//			public readonly static string Vnd_gtw									= @"model/vnd.gtw"  ; // [Ozaki]
//			public readonly static string Vnd_mts									= @"model/vnd.mts"  ; // [Rabinovitch]
//			public readonly static string Vnd_parasolid_transmit_binary			= @"model/vnd.parasolid.transmit.binary"   ; // [Parasolid]
//			public readonly static string Vnd_parasolid_transmit_text				= @"model/vnd.parasolid.transmit.text"    ; // [Parasolid]
//			public readonly static string Vnd_vtu									= @"model/vnd.vtu"  ; // [Rabinovitch]
//			public readonly static string vrml									= @"model/vrml"  ; // [RFC2077]
//		}

		public static class Multipart
		{
			public readonly static string Alternative								= @"multipart/alternative"   ; // [RFC2045,RFC2046]
			public readonly static string Appledouble								= @"multipart/appledouble"   ; // [Faltstrom]
			public readonly static string Byteranges								= @"multipart/byteranges"  ; // [RFC2068]
			public readonly static string Digest									= @"multipart/digest"    ; // [RFC2045,RFC2046]
			public readonly static string Encrypted								= @"multipart/encrypted"    ; // [RFC1847]
			public readonly static string Form_data								= @"multipart/form-data"    ; // [RFC2388]
			public readonly static string Header_set								= @"multipart/header-set"  ; // [Crocker]
			public readonly static string Mixed									= @"multipart/mixed"   ; // [RFC2045,RFC2046]
			public readonly static string Parallel								= @"multipart/parallel"   ; // [RFC2045,RFC2046]
			public readonly static string Related									= @"multipart/related"  ; // [RFC2387]
			public readonly static string Report									= @"multipart/report"    ; // [RFC1892]
			public readonly static string Signed									= @"multipart/signed"    ; // [RFC1847]
			public readonly static string Voice_message							= @"multipart/voice-message"  ; // [RFC2421,RFC2423]
		}
		
		public static class Text
		{
			public readonly static string Calendar								= @"text/calendar"   ; // [RFC2445]
			public readonly static string Css										= @"text/css"    ; // [RFC2318]
			public readonly static string Directory								= @"text/directory"    ; // [RFC2425]
			public readonly static string Dns										= @"text/dns"    ; // [RFC-josefsson-mime-dns-02.txt]
			public readonly static string Enriched								= @"text/enriched"   ; // [RFC1896]
			public readonly static string Html									= @"text/html"  ; // [RFC2854]
			public readonly static string Parityfec								= @"text/parityfec"    ; // [RFC3009]
			public readonly static string Plain									= @"text/plain"   ; // [RFC2046, RFC3676]
			public readonly static string Prs_fallenstein_rst						= @"text/prs.fallenstein.rst"  ; // [Fallenstein]
			public readonly static string Prs_lines_tag							= @"text/prs.lines.tag"  ; // [Lines]
			public readonly static string Rfc822_headers							= @"text/rfc822-headers"   ; // [RFC1892]
			public readonly static string Richtext								= @"text/richtext"   ; // [RFC2045,RFC2046]
			public readonly static string Rtf										= @"text/rtf"    ; // [Lindner]
			public readonly static string Sgml									= @"text/sgml"  ; // [RFC1874]
			public readonly static string T140									= @"text/t140"  ; // [RFC-ietf-avt-rfc2793bis-09.txt]
			public readonly static string Tab_separated_values					= @"text/tab-separated-values"   ; // [Lindner]
			public readonly static string Uri_list								= @"text/uri-list"   ; // [RFC2483]
			public readonly static string Vnd_abc									= @"text/vnd.abc"  ; // [Allen]
			public readonly static string Vnd_curl								= @"text/vnd.curl"   ; // [Byrnes]
			public readonly static string Vnd_DMClientScript						= @"text/vnd.DMClientScript"    ; // [Bradley]
			public readonly static string Vnd_esmertec_theme_descriptor			= @"text/vnd.esmertec.theme-descriptor"   ; // [Eilemann]
			public readonly static string Vnd_fly									= @"text/vnd.fly"  ; // [Gurney]
			public readonly static string Vnd_fmi_flexstor						= @"text/vnd.fmi.flexstor"  ; // [Hurtta]
			public readonly static string Vnd_in3d_3dml							= @"text/vnd.in3d.3dml"  ; // [Powers]
			public readonly static string Vnd_in3d_spot							= @"text/vnd.in3d.spot"  ; // [Powers]
			public readonly static string Vnd_IPTC_NewsML							= @"text/vnd.IPTC.NewsML"    ; // [IPTC]
			public readonly static string Vnd_IPTC_NITF							= @"text/vnd.IPTC.NITF"  ; // [IPTC]
			public readonly static string Vnd_latex_z								= @"text/vnd.latex-z"   ; // [Lubos]
			public readonly static string Vnd_motorola_reflex						= @"text/vnd.motorola.reflex"  ; // [Patton]
			public readonly static string Vnd_ms_mediapackage						= @"text/vnd.ms-mediapackage"  ; // [Nelson]
			public readonly static string Vnd_net2phone_commcenter_command		= @"text/vnd.net2phone.commcenter.command"   ; // [Xie]
			public readonly static string Vnd_sun_j2me_app_descriptor				= @"text/vnd.sun.j2me.app-descriptor"    ; // [G.Adams]
			public readonly static string Vnd_wap_si								= @"text/vnd.wap.si"  ; // [WAP-Forum]
			public readonly static string Vnd_wap_sl								= @"text/vnd.wap.sl"  ; // [WAP-Forum]
			public readonly static string Vnd_wap_wml								= @"text/vnd.wap.wml"   ; // [Stark]
			public readonly static string Vnd_wap_wmlscript						= @"text/vnd.wap.wmlscript"   ; // [Stark]
			public readonly static string Xml										= @"text/xml"    ; // [RFC3023]
			public readonly static string Xml_external_parsed_entity				= @"text/xml-external-parsed-entity"   ; // [RFC3023]
		}

//		public class Video
//		{
//			public readonly static string 3gpp									= @"video/3gpp";       // [RFC3839]
//			public readonly static string bmpeg									= @"video/BMPEG";        // [RFC3555]
//			public readonly static string bt656									= @"video/BT656"   ; // [RFC3555]
//			public readonly static string celb									= @"video/CelB"  ; // [RFC3555]
//			public readonly static string dv										= @"video/DV"   ; // [RFC3189]
//			public readonly static string h261									= @"video/H261"  ; // [RFC3555]
//			public readonly static string h263									= @"video/H263"  ; // [RFC3555]
//			public readonly static string h263_1998								= @"video/H263-1998"    ; // [RFC3555]
//			public readonly static string h263_2000								= @"video/H263-2000"    ; // [RFC3555]
//			public readonly static string h264									= @"video/H264"  ; // [RFC-ietf-avt-rtp-h264-11.txt]
//			public readonly static string jpeg									= @"video/JPEG"  ; // [RFC3555]
//			public readonly static string mj2										= @"video/MJ2"    ; // [RFC3745]
//			public readonly static string mp1s									= @"video/MP1S"  ; // [RFC3555]
//			public readonly static string mp2p									= @"video/MP2P"  ; // [RFC3555]
//			public readonly static string mp2t									= @"video/MP2T"  ; // [RFC3555]
//			public readonly static string mp4v_es									= @"video/MP4V-ES"  ; // [RFC3016]
//			public readonly static string mpv										= @"video/MPV"    ; // [RFC3555]
//			public readonly static string mpeg									= @"video/mpeg"  ; // [RFC2045,RFC2046]
//			public readonly static string mpeg4_generic							= @"video/mpeg4-generic"  ; // [RFC3640]
//			public readonly static string nv										= @"video/nv"   ; // [RFC3555]
//			public readonly static string parityfec								= @"video/parityfec"    ; // [RFC3009]
//			public readonly static string pointer									= @"video/pointer"  ; // [RFC2862]
//			public readonly static string quicktime								= @"video/quicktime"    ; // [Lindner]
//			public readonly static string SMPTE292M								= @"video/SMPTE292M" ; // [RFC3497]
//			public readonly static string Vnd_fvt									= @"video/vnd.fvt"  ; // [Fuldseth]
//			public readonly static string Vnd_motorola_video						= @"video/vnd.motorola.video"    ; // [McGinty]
//			public readonly static string Vnd_motorola_videop						= @"video/vnd.motorola.videop"  ; // [McGinty]
//			public readonly static string Vnd_mpegurl								= @"video/vnd.mpegurl"   ; // [Recktenwald]
//			public readonly static string Vnd_nokia_interleaved_multimedia		= @"video/vnd.nokia.interleaved-multimedia"   ; // [Kangaslampi]
//			public readonly static string Vnd_objectvideo							= @"video/vnd.objectvideo"    ; // [Clark]
//			public readonly static string Vnd_sealed_mpeg1						= @"video/vnd.sealed.mpeg1"  ; // [Petersen]
//			public readonly static string Vnd_sealed_mpeg4						= @"video/vnd.sealed.mpeg4"  ; // [Petersen]
//			public readonly static string Vnd_sealed_swf							= @"video/vnd.sealed.swf"   ; // [Petersen]
//			public readonly static string Vnd_sealedmedia_softseal_mov			= @"video/vnd.sealedmedia.softseal.mov"  ; // [Petersen]
//			public readonly static string Vnd_vivo								= @"video/vnd.vivo"   ; // [Wolfe]
//		}
	}
}
